project:
  type: website
  output-dir: slides
  resources:
    - "*.html"
website: 
  title: "CPSC 330 Section 103 Slides"
  page-navigation: true
  navbar:
    title: "CPSC 330 Section 103"
    background: light
    left:
      - href: index.qmd
        text: Home
      - href: slides.qmd
        text: Slides        
  sidebar:
    - id: slides
      contents:
        - slides-*.qmd
format:
  html:
    theme: 
      - zephyr
      - styles.scss
    toc: false
    lightbox: true
    css: styles.css
          
editor:
  render-on-save: true

execute:
  freeze: auto
  