---
title: "Lecture 21: Survival analysis"
author: "Firas Moosvi"
format: 
    revealjs:
      embed-resources: true
      slide-number: true
      smaller: true
      center: true
      logo: img/UBC-CS-logo.png
      theme: [night, slides.scss]
      resources:
        - data/
        - img/        
---

## Announcements

- Test 3 update
  - One of the MCQ was mistakenly set to 4 marks instead of 1, need to fix that
  - Resolution will mean everyone's score will increase 
  - Scores will be released after
- HW9 has been released!
- Practice Workspace question for the final exam will be posted on PrairieLearn this weekend to help you prepare

## Announcements (cont'd)

- We are in the home stretch now! Monday will be the last class
- Tutorials are ON Tues/Wed
- NO tutorials on Thurs/Fri
- Office hours as usual next week

## Wrap-up Time Series from last class 

## Recap: Time Series Analysis

# Clicker 21.1

**Select all of the following statements which are TRUE.**

- (A) We need to be careful when splitting the data when working with time series data.
- (B) Cross-validation in time series can be randomly applied like in other machine learning tasks.
- (C) In time series forecasting, the future value of a series can only be predicted based on its past values and cannot incorporate other variables.
- (D) When we used RandomForestRegressor model on the POSIX time feature, it predicted a straight line on the test data because tree-based models are inherently unable to extrapolate (i.e., make predictions outside the - range of the training data).

# Introduction to Survival Analysis

## Group Work: Class Demo & Live Coding

For this demo, each student should [click this link](https://github.com/new?template_name=lecture21_demo&template_owner=ubc-cpsc330) to create a new repo in their accounts, then clone that repo locally to follow along with the demo from today.

# Clicker 21.2

**Select all of the following statements which are TRUE.**

- (A) Right censoring occurs when the endpoint of event has not been observed for all study subjects by the end of the study period.
- (B) Right censoring implies that the data is missing completely at random.
- (C) In the presence of right-censored data, binary classification models can be applied directly without any modifications or special considerations.
- (D) If we apply the Ridge regression model to predict tenure in right censored data, we are likely to underestimate it because the tenure observed in our data is shorter than what it would be in reality.