on:
  workflow_dispatch:
  push:
    branches: main

name: Quarto Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13' 

      - name: Install Python and pip
        run: sudo apt-get install python3 python3-pip

      - name: cache installation
        uses: actions/cache@v3
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ env.pythonLocation }}-${{ hashFiles('setup.py') }}-${{ hashFiles('requirements.txt') }}

      - id: install-graphviz-linux
        name: Install Graphviz on Linux
        # if: runner.os == 'Linux'
        # shell: bash
        run: |
          # Install Graphviz on Linux
          sudo apt update
          sudo apt install -qy gsfonts
          sudo apt -qq list fonts-liberation gsfonts
          sudo apt install -qy graphviz
          sudo apt -y autoremove --purge
          sudo apt -y autoclean
          sudo apt clean

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
          path: website
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
